using System;
using System.Linq;
using NUnit.Framework;
using Xeon.XDebugger.Model;

namespace Xeon.XDebugger.Tests
{
    public enum TestEnum { Alpha, Beta, Gamma }

    [TestFixture]
    public class EnumDropdownModelTests
    {
        [Test]
        public void Constructor_WithIndex_SetsTitle()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null);
            Assert.AreEqual("Enum", model.Title);
        }

        [Test]
        public void Constructor_WithIndex_SetsSelectedIndex()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 1, null);
            Assert.AreEqual(1, model.SelectedIndex);
        }

        [Test]
        public void Constructor_WithIndex_SetsValue()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 1, null);
            Assert.AreEqual(TestEnum.Beta, model.Value);
        }

        [Test]
        public void Constructor_WithEnumValue_SetsCorrectIndex()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", TestEnum.Gamma, null);
            Assert.AreEqual(2, model.SelectedIndex);
        }

        [Test]
        public void Constructor_WithEnumValue_SetsValue()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", TestEnum.Beta, null);
            Assert.AreEqual(TestEnum.Beta, model.Value);
        }

        [Test]
        public void Constructor_SetsPriority()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null, 3);
            Assert.AreEqual(3, model.Priority);
        }

        [Test]
        public void Labels_AutoGeneratedFromEnumNames()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null);
            var expected = Enum.GetNames(typeof(TestEnum)).ToList();
            Assert.AreEqual(expected, model.Labels);
        }

        [Test]
        public void Value_ReturnsCorrectEnumForEachIndex()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null);

            Assert.AreEqual(TestEnum.Alpha, model.Value);

            model.SelectedIndex = 1;
            Assert.AreEqual(TestEnum.Beta, model.Value);

            model.SelectedIndex = 2;
            Assert.AreEqual(TestEnum.Gamma, model.Value);
        }

        [Test]
        public void IEnumDropdownModel_Value_ReturnsEnum()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", TestEnum.Beta, null);
            IEnumDropdownModel interfaceModel = model;

            Assert.AreEqual(TestEnum.Beta, interfaceModel.Value);
        }

        [Test]
        public void SelectedIndex_Set_DoesNotFireCallback()
        {
            var callbackFired = false;
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, _ => callbackFired = true);

            model.SelectedIndex = 2;

            Assert.IsFalse(callbackFired);
        }

        [Test]
        public void SelectedIndex_Set_FiresChangedEvent()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null);
            var changedFired = false;
            model.Changed += () => changedFired = true;

            model.SelectedIndex = 1;

            Assert.IsTrue(changedFired);
        }

        [Test]
        public void SetSelectedIndex_WithNotifyTrue_FiresCallback()
        {
            TestEnum? receivedValue = null;
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, v => receivedValue = v);

            model.SetSelectedIndex(2, true);

            Assert.AreEqual(TestEnum.Gamma, receivedValue);
        }

        [Test]
        public void SetSelectedIndex_WithNotifyFalse_DoesNotFireCallback()
        {
            var callbackFired = false;
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, _ => callbackFired = true);

            model.SetSelectedIndex(1, false);

            Assert.IsFalse(callbackFired);
        }

        [Test]
        public void SetSelectedIndex_ClampsToRange()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null);

            model.SetSelectedIndex(100, false);
            Assert.AreEqual(2, model.SelectedIndex);

            model.SetSelectedIndex(-5, false);
            Assert.AreEqual(0, model.SelectedIndex);
        }

        [Test]
        public void SetSelectedIndex_FiresChangedEvent()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null);
            var changedFired = false;
            model.Changed += () => changedFired = true;

            model.SetSelectedIndex(1, false);

            Assert.IsTrue(changedFired);
        }

        [Test]
        public void SetValue_TypedEnum_SetsCorrectIndex()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null);

            model.SetValue(TestEnum.Gamma, false);

            Assert.AreEqual(2, model.SelectedIndex);
            Assert.AreEqual(TestEnum.Gamma, model.Value);
        }

        [Test]
        public void SetValue_TypedEnum_WithNotifyTrue_FiresCallback()
        {
            TestEnum? receivedValue = null;
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, v => receivedValue = v);

            model.SetValue(TestEnum.Beta, true);

            Assert.AreEqual(TestEnum.Beta, receivedValue);
        }

        [Test]
        public void SetValue_TypedEnum_WithNotifyFalse_DoesNotFireCallback()
        {
            var callbackFired = false;
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, _ => callbackFired = true);

            model.SetValue(TestEnum.Beta, false);

            Assert.IsFalse(callbackFired);
        }

        [Test]
        public void SetValue_EnumBase_SetsCorrectIndex()
        {
            IEnumDropdownModel model = new EnumDropdownModel<TestEnum>("Enum", 0, null);

            model.SetValue((Enum)TestEnum.Gamma, false);

            Assert.AreEqual(TestEnum.Gamma, model.Value);
        }

        [Test]
        public void SetValue_EnumBase_WithNotifyTrue_FiresCallback()
        {
            TestEnum? receivedValue = null;
            IEnumDropdownModel model = new EnumDropdownModel<TestEnum>("Enum", 0, v => receivedValue = v);

            model.SetValue((Enum)TestEnum.Beta, true);

            Assert.AreEqual(TestEnum.Beta, receivedValue);
        }

        [Test]
        public void NotifySelectedIndexChangedFromView_FiresCallback()
        {
            TestEnum? receivedValue = null;
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, v => receivedValue = v);

            model.NotifySelectedIndexChangedFromView(1);

            Assert.AreEqual(TestEnum.Beta, receivedValue);
        }

        [Test]
        public void NotifySelectedIndexChangedFromView_ChangesIndex()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null);

            model.NotifySelectedIndexChangedFromView(2);

            Assert.AreEqual(2, model.SelectedIndex);
            Assert.AreEqual(TestEnum.Gamma, model.Value);
        }

        [Test]
        public void NotifySelectedIndexChangedFromView_FiresChangedEvent()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null);
            var changedFired = false;
            model.Changed += () => changedFired = true;

            model.NotifySelectedIndexChangedFromView(1);

            Assert.IsTrue(changedFired);
        }

        [Test]
        public void SetSelectedIndex_NullCallback_DoesNotThrow()
        {
            var model = new EnumDropdownModel<TestEnum>("Enum", 0, null);

            Assert.DoesNotThrow(() => model.SetSelectedIndex(1, true));
        }
    }
}
